name: oepd8
recipe: drupal8
services:
  appserver:
    webroot: web
    xdebug: true
    config:
      php: php.ini
    build_as_root:
      - apt-get update -y
      - apt install libxslt1-dev -y
      - docker-php-ext-install xsl
  db2:
    type: mysql:5.7
    creds:
      user: drupal7
      password: drupal7
      database: drupal7
