name: gtpd8
recipe: drupal8
services:
  appserver:
    webroot: web
    xdebug: true
    config:
      php: php.ini
  db2:
    type: mysql:5.7
    creds:
      user: drupal7
      password: drupal7
      database: drupal7
